-- Add migration script here
CREATE TABLE game_week_players (
    player_id INTEGER NOT NULL REFERENCES players (id),
    game_week_id INTEGER NOT NULL REFERENCES game_weeks (id),
    minutes SMALLINT NOT NULL,
    goals_scored SMALLINT NOT NULL,
    assists SMALLINT NOT NULL,
    clean_sheets SMALLINT NOT NULL,
    goals_conceded SMALLINT NOT NULL,
    own_goals SMALLINT NOT NULL,
    penalties_saved SMALLINT NOT NULL,
    penalties_missed SMALLINT NOT NULL,
    yellow_cards SMALLINT NOT NULL,
    red_cards SMALLINT NOT NULL,
    saves SMALLINT NOT NULL,
    bonus SMALLINT NOT NULL,
    bps SMALLINT NOT NULL,
    influence REAL NOT NULL,
    creativity REAL NOT NULL,
    threat REAL NOT NULL,
    ict_index REAL NOT NULL,
    starts SMALLINT NOT NULL,
    expected_goals REAL NOT NULL,
    expected_assists REAL NOT NULL,
    expected_goal_involvements REAL NOT NULL,
    expected_goals_conceded REAL NOT NULL,
    total_points SMALLINT NOT NULL,
    in_dreamteam BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW (),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW (),
    PRIMARY KEY (player_id, game_week_id)
);
