-- Add migration script here
CREATE TABLE players (
    id INTEGER PRIMARY KEY,
    can_transact BOOLEAN NOT NULL,
    can_select BOOLEAN NOT NULL,
    chance_of_playing_next_round SMALLINT,
    chance_of_playing_this_round SMALLINT,
    code INTEGER NOT NULL,
    cost_change_event SMALLINT NOT NULL,
    cost_change_event_fall SMALLINT NOT NULL,
    cost_change_start SMALLINT NOT NULL,
    cost_change_start_fall SMALLINT NOT NULL,
    dreamteam_count SMALLINT NOT NULL,
    element_type SMALLINT NOT NULL,
    ep_next VARCHAR(10) NOT NULL,
    ep_this VARCHAR(10) NOT NULL,
    event_points SMALLINT NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    form VARCHAR(10) NOT NULL,
    in_dreamteam BOOLEAN NOT NULL,
    news TEXT NOT NULL,
    news_added TIMESTAMP
    WITH
        TIME ZONE,
        now_cost SMALLINT NOT NULL,
        photo VARCHAR(100) NOT NULL,
        points_per_game VARCHAR(10) NOT NULL,
        removed BOOLEAN NOT NULL,
        second_name VARCHAR(50) NOT NULL,
        selected_by_percent VARCHAR(10) NOT NULL,
        special BOOLEAN NOT NULL,
        squad_number SMALLINT,
        status VARCHAR(20) NOT NULL,
        team SMALLINT NOT NULL,
        team_code SMALLINT NOT NULL,
        total_points SMALLINT NOT NULL,
        transfers_in INTEGER NOT NULL,
        transfers_in_event INTEGER NOT NULL,
        transfers_out INTEGER NOT NULL,
        transfers_out_event INTEGER NOT NULL,
        value_form VARCHAR(10) NOT NULL,
        value_season VARCHAR(10) NOT NULL,
        web_name VARCHAR(50) NOT NULL,
        region SMALLINT,
        team_join_date DATE,
        minutes SMALLINT NOT NULL,
        goals_scored SMALLINT NOT NULL,
        assists SMALLINT NOT NULL,
        clean_sheets SMALLINT NOT NULL,
        goals_conceded SMALLINT NOT NULL,
        own_goals SMALLINT NOT NULL,
        penalties_saved SMALLINT NOT NULL,
        penalties_missed SMALLINT NOT NULL,
        yellow_cards SMALLINT NOT NULL,
        red_cards SMALLINT NOT NULL,
        saves SMALLINT NOT NULL,
        bonus SMALLINT NOT NULL,
        bps SMALLINT NOT NULL,
        influence VARCHAR(10) NOT NULL,
        creativity VARCHAR(10) NOT NULL,
        threat VARCHAR(10) NOT NULL,
        ict_index VARCHAR(10) NOT NULL,
        starts SMALLINT NOT NULL,
        expected_goals VARCHAR(10) NOT NULL,
        expected_assists VARCHAR(10) NOT NULL,
        expected_goal_involvements VARCHAR(10) NOT NULL,
        expected_goals_conceded VARCHAR(10) NOT NULL,
        influence_rank SMALLINT NOT NULL,
        influence_rank_type SMALLINT NOT NULL,
        creativity_rank SMALLINT NOT NULL,
        creativity_rank_type SMALLINT NOT NULL,
        threat_rank SMALLINT NOT NULL,
        threat_rank_type SMALLINT NOT NULL,
        ict_index_rank SMALLINT NOT NULL,
        ict_index_rank_type SMALLINT NOT NULL,
        corners_and_indirect_freekicks_order SMALLINT,
        corners_and_indirect_freekicks_text TEXT NOT NULL,
        direct_freekicks_order SMALLINT,
        direct_freekicks_text TEXT NOT NULL,
        penalties_order SMALLINT,
        penalties_text TEXT NOT NULL,
        expected_goals_per_90 REAL NOT NULL,
        saves_per_90 REAL NOT NULL,
        expected_assists_per_90 REAL NOT NULL,
        expected_goal_involvements_per_90 REAL NOT NULL,
        expected_goals_conceded_per_90 REAL NOT NULL,
        goals_conceded_per_90 REAL NOT NULL,
        now_cost_rank SMALLINT NOT NULL,
        now_cost_rank_type SMALLINT NOT NULL,
        form_rank SMALLINT NOT NULL,
        form_rank_type SMALLINT NOT NULL,
        points_per_game_rank SMALLINT NOT NULL,
        points_per_game_rank_type SMALLINT NOT NULL,
        selected_rank SMALLINT NOT NULL,
        selected_rank_type SMALLINT NOT NULL,
        starts_per_90 REAL NOT NULL,
        clean_sheets_per_90 REAL NOT NULL
);
