-- Add migration script here
CREATE TABLE player_history (
    player_id smallint NOT NULL REFERENCES players (id),
    fixture_id smallint NOT NULL REFERENCES fixtures (id),
    opponent_team smallint NOT NULL,
    total_points smallint NOT NULL,
    was_home boolean NOT NULL,
    kickoff_time timestamptz NOT NULL,
    team_h_score smallint,
    team_a_score smallint,
    round smallint NOT NULL REFERENCES game_weeks (id),
    minutes smallint NOT NULL,
    goals_scored smallint NOT NULL,
    assists smallint NOT NULL,
    clean_sheets smallint NOT NULL,
    goals_conceded smallint NOT NULL,
    own_goals smallint NOT NULL,
    penalties_saved smallint NOT NULL,
    penalties_missed smallint NOT NULL,
    yellow_cards smallint NOT NULL,
    red_cards smallint NOT NULL,
    saves smallint NOT NULL,
    bonus smallint NOT NULL,
    bps smallint NOT NULL,
    influence real NOT NULL,
    creativity real NOT NULL,
    threat real NOT NULL,
    ict_index real NOT NULL,
    starts smallint NOT NULL,
    expected_goals real NOT NULL,
    expected_assists real NOT NULL,
    expected_goal_involvements real NOT NULL,
    expected_goals_conceded real NOT NULL,
    value smallint NOT NULL,
    transfers_balance integer NOT NULL,
    selected integer NOT NULL,
    transfers_in integer NOT NULL,
    transfers_out integer NOT NULL,
    PRIMARY KEY (player_id, fixture_id)
);
