-- Add migration script here
CREATE TABLE player_history_past (
    player_id smallint NOT NULL REFERENCES players (id),
    season_name text NOT NULL,
    element_code integer NOT NULL,
    start_cost smallint NOT NULL,
    end_cost smallint NOT NULL,
    total_points smallint NOT NULL,
    minutes smallint NOT NULL,
    goals_scored smallint NOT NULL,
    assists smallint NOT NULL,
    clean_sheets smallint NOT NULL,
    goals_conceded smallint NOT NULL,
    own_goals smallint NOT NULL,
    penalties_saved smallint NOT NULL,
    penalties_missed smallint NOT NULL,
    yellow_cards smallint NOT NULL,
    red_cards smallint NOT NULL,
    saves smallint NOT NULL,
    bonus smallint NOT NULL,
    bps smallint NOT NULL,
    influence real NOT NULL,
    creativity real NOT NULL,
    threat real NOT NULL,
    ict_index real NOT NULL,
    starts smallint NOT NULL,
    expected_goals real NOT NULL,
    expected_assists real NOT NULL,
    expected_goal_involvements real NOT NULL,
    expected_goals_conceded real NOT NULL,
    PRIMARY KEY (player_id, season_name)
);
